site_name: Rumble Chat Actor Docs

theme:
  name: "material"
#  logo: assets/cocorum_icon.png

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - modules_ref/main.md
    - modules_ref/actions.md
    - modules_ref/commands.md
    - modules_ref/misc.md
    - modules_ref/utils.md
    - modules_ref/static.md
    - action_properties.md
  - explanation.md
